# Site settings
title: A Plan for Russ
email: wbaylusholliday@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The need for ethical and instructional approaches necessary for Russ’ 
  success in school.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wbholliday.github.io" # the base hostname & protocol for your site
github_username:  wbholliday
collections:
- intros

# Build settings
markdown: kramdown
